authentication/urls.py
from django.urls import path, re_path, include
from . import views
from django.conf.urls import url


app_name = 'authentication'
urlpatterns = [
    path('login', views.logmein, name='login'),
    path('logout', views.logmeout, name='logout'),
    path('signup', views.signup, name='signup'),
    re_path(r'^account_activation_sent/$', views.account_activation_sent,
            name='account_activation_sent'),
    re_path(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate,
        name='activate'
    ),


]

djangogamelancer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # starting language paths with predefined prefixes
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(

    path(_('authentication/'),
         include('authentication.urls', namespace='authentication')),
    path(_('feedback/'),
         include('feedback.urls', namespace='feedback')),
    path(_('admin/'), admin.site.urls),
    path((''), include('userpanel.urls', namespace='userpanel')),
    path(_('verification/'), include('verification.urls', namespace='verification')),
    path("api/", include("simple-feedback.urls")),
    prefix_default_language=True,
)

# urlpatterns += staticfiles_urlpatterns()  # not sure if works
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)  # not sure if works

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'
urlpatterns = [
    path('leave_feedback/<str:recipient>/',
         views.leave_feedback.as_view(), name='leavefeedback'),
    path('check_feedback/<str:feeedback_for>/',
         views.check_feedback.as_view(), name='checkfeedback')

]

userpanel/urls.py
from django.urls import path
from . import views

app_name = 'userpanel'
urlpatterns = [
    path('', views.index, name='index'),
    path('settings/profile_settings/',
         views.profile_settings, name='profilesettings'),
]

verification/urls.py
from django.urls import path
from . import views

app_name = 'verification'
urlpatterns = [
    path('', views.upload_document, name='upload')
]

templates/base_template/navigation_menu.html
{% block navigation %} {% load thumbnail %}
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          {% thumbnail user.profile_pic "64x64" crop="center" as im %}
          <img
            alt="image"
            class="rounded-circle"
            src="{{ im.url }}"
            width="{{ im.width }}"
            height="{{ im.height }}"
          />
          {% endthumbnail %}

          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="block m-t-xs font-bold"
              ><p>Welcome {{ user.username }}</p></span
            >
            <span class="text-muted text-xs block"
              >Art Director <b class="caret"></b
            ></span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a class="dropdown-item" href="profile.html">Profile</a></li>
            <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
            <li><a class="dropdown-item" href="mailbox.html">Mailbox</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="login.html">Logout</a></li>
          </ul>
        </div>
        <div class="logo-element">IN+</div>
      </li>

      <li>
        <a href="{% url 'admin:index' %}"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">{% url 'admin:index' %}</span></a
        >
      </li>
      <li>
        <a href="index.html"
          ><i class="fa fa-th-large"></i>
          <span class="nav-label">Dashboards</span>
          <span class="fa arrow"></span
        ></a>
        <ul class="nav nav-second-level collapse">
          <li><a href="index.html">Dashboard v.1</a></li>
          <li><a href="dashboard_2.html">Dashboard v.2</a></li>
          <li><a href="dashboard_3.html">Dashboard v.3</a></li>
          <li><a href="dashboard_4_1.html">Dashboard v.4</a></li>
          <li><a href="dashboard_5.html">Dashboard v.5 </a></li>
        </ul>
      </li>

      <li>
        <a href="#"
          ><i class="fa fa-bar-chart-o"></i>
          <span class="nav-label">Graphs</span><span class="fa arrow"></span
        ></a>
        <ul class="nav nav-second-level collapse">
          <li><a href="graph_flot.html">Flot Charts</a></li>
          <li><a href="graph_morris.html">Morris.js Charts</a></li>
          <li><a href="graph_rickshaw.html">Rickshaw Charts</a></li>
          <li><a href="graph_chartjs.html">Chart.js</a></li>
          <li><a href="graph_chartist.html">Chartist</a></li>
          <li><a href="c3.html">c3 charts</a></li>
          <li><a href="graph_peity.html">Peity Charts</a></li>
          <li><a href="graph_sparkline.html">Sparkline Charts</a></li>
        </ul>
      </li>
      <li>
        <a href="mailbox/"
          ><i class="fa fa-envelope"></i> <span class="nav-label">Mailbox </span
          ><span class="label label-warning float-right">16/24</span></a
        >
        <ul class="nav nav-second-level collapse">
          <li><a href="mailbox/">Inbox</a></li>
          <li><a href="mail_detail/">Email view</a></li>
          <li><a href="mail_compose/">Compose email</a></li>
          <li><a href="email_template/">Email templates</a></li>
        </ul>
      </li>

      <li>
        <a href="boosting/select_elo/"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">Start Boosting</span></a
        >
      </li>
      <li>
        <a href="couching/"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">Start Couching</span></a
        >
      </li>
      <li>
        <a href="esport/"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">Start Esport carrier</span></a
        >
      </li>
      <li>
        <a href="caster/"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">Start Caster carrier</span></a
        >
      </li>

      <li>
        <a href="index.html"
          ><i class="fa fa-th-large"></i>
          <span class="nav-label">Feedback</span> <span class="fa arrow"></span
        ></a>
        <ul class="nav nav-second-level collapse">
          <li>
            <a href="{% url 'feedback:leavefeedback' 'Septio' %}"
              >Leave Feedback</a
            >
          </li>
          <li>
            <a href="{% url 'feedback:checkfeedback' 'Septio' %}"
              >Your Feedback</a
            >
          </li>
          <li><a href="dashboard_2.html">other shit</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'authentication:signup' %}"
          ><i class="fa fa-diamond"></i>
          <span class="nav-label">Sign Up </span></a
        >
      </li>

      <li>
        <a href="index.html"
          ><i class="fa fa-th-large"></i>
          <span class="nav-label">Settings</span> <span class="fa arrow"></span
        ></a>
        <ul class="nav nav-second-level collapse">
          <li>
            <a href="{% url 'userpanel:profilesettings' %}">Profile Settings</a>
          </li>
          <li><a href="dashboard_2.html">other shit</a></li>
          <li><a href="dashboard_2.html">other shit</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'verification:upload' %}"
          ><i class="fa fa-bar-chart-o"></i>
          <span class="nav-label">Verificate yourself </span></a
        >
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

templates/base_template/top_navigation_menu.html
{% load static i18n %}
{% load my_tags %}
{% get_static_prefix as STATIC_PREFIX %}
{% get_current_language as LANGUAGE_CODE %}

<nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Your feedback score: {{ user.feedbackscore}}</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="img/a7.jpg">
                                </a>
                                <div class="media-body">
                                    <small class="float-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="img/a4.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="img/profile.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html" class="dropdown-item">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="profile.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="float-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="grid_options.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html" class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>

                
                
                {% if request.user.is_authenticated %}
                {% logout_tag %}
                {% else %}                
                {% login_form %}
                {% endif %}
                <li>
                    {{ LANGUAGE_CODE }}
                </li>
                <form action="{% url 'set_language'%}" method="post">{% csrf_token %}
                    <input type="hidden" name="text" value="{{ redirect_to }}">
                    <select name="language" id="">
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE.CODE %} selected {% endif %}>
                            {{language.name_local}} ({{ language.code }})
                        </option>
                    {% endfor %}
                    </select>
                    <input type="submit" value="go">
                </form>
            </ul>

        </nav>